CheckList/Models/Check.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CheckList.Models
{
    public class Check
    {
        public int CheckId { get; set; }
        public String CheckDescription { get; set; }
        public bool CheckIsDone { get; set; }
        public DateTime CheckDueDate { get; set; }
        public virtual ApplicationUser CheckUser { get; set; }
        public bool CheckIsNotified { get; set; }
    }
}

CheckList/Controllers/ChecksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CheckList.Models;
using Microsoft.AspNet.Identity;

namespace CheckList.Controllers
{
    public class ChecksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Checks
        public ActionResult Index()
        {
            return View();
        }

        private IEnumerable<Check> GetChecks()
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(u => u.Id == currentUserId);
            IEnumerable<Check> checks = db.Checks.ToList().Where(u => u.CheckUser == currentUser).OrderBy(u => u.CheckDueDate);
            int count = 0;
            foreach(Check check in checks)
            {
                if (check.CheckIsDone)
                {
                    count++;
                }
            }

            ViewBag.Percent = Math.Round(100f * ((float)count/(float)checks.Count()));
            IEnumerable<Check> incomingChecks = checks.Where(x => x.CheckIsDone == false && !x.CheckIsNotified).Where(x => DateTime.Compare(x.CheckDueDate.AddHours(12), DateTime.Now) > 0);
            ViewData["Item"] = "";
            if (incomingChecks != null && incomingChecks.Count() >= 1)
            {
                ViewData["Item"] = incomingChecks.First().CheckDescription;
                ViewData["ItemId"] = incomingChecks.First().CheckId;
            }
            return checks;
        }

        [HttpPost]
        public ActionResult UpdateCheckNotify(int id)
        {
            Check incomingCheck = db.Checks.FirstOrDefault(c =>(c.CheckId == id));
            incomingCheck.CheckIsNotified = true;
            db.SaveChanges();
            return Json(true, JsonRequestBehavior.AllowGet);
        }



        public ActionResult CreateCheckTable()
        {
            return PartialView("_CheckTable", GetChecks());
        }

        // GET: Checks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Check check = db.Checks.Find(id);
            if (check == null)
            {
                return HttpNotFound();
            }
            return View(check);
        }

        // GET: Checks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Checks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CheckId,CheckDescription,CheckIsDone,CheckDueDate")] Check check)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(user => user.Id == currentUserId);
                check.CheckUser = currentUser;
                check.CheckIsNotified = false;
                db.Checks.Add(check);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(check);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AJAXCreate([Bind(Include = "CheckId,CheckDescription,CheckDueDate")] Check check)
        {
            if (ModelState.IsValid)
            {
                if(check.CheckDescription == null || check.CheckDescription == "")
                {//if description is empty
                    return View(check);
                }
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(user => user.Id == currentUserId);
                check.CheckUser = currentUser;
                check.CheckIsDone = false;
                check.CheckIsNotified = false;
                db.Checks.Add(check);
                db.SaveChanges();
            }

            return PartialView("_CheckTable", GetChecks());
        }

        // GET: Checks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Check check = db.Checks.Find(id);
            if (check == null)
            {
                return HttpNotFound();
            }
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(user => user.Id == currentUserId);
            if(check.CheckUser != currentUser)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(check);
        }

        // POST: Checks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CheckId,CheckDescription,CheckIsDone,CheckDueDate")] Check check)
        {
            if (ModelState.IsValid)
            {
                db.Entry(check).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(check);
        }

        [HttpPost]
        public ActionResult AJAXEdit(int? id, bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Check check = db.Checks.Find(id);

            if (check == null)
            {
                return HttpNotFound();
            }
            else
            {
                check.CheckIsDone = value;
                db.Entry(check).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_CheckTable", GetChecks());
            }
        }

        // GET: Checks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Check check = db.Checks.Find(id);
            if (check == null)
            {
                return HttpNotFound();
            }
            return View(check);
        }

        // POST: Checks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Check check = db.Checks.Find(id);
            db.Checks.Remove(check);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CheckList/Views/Checks/Create.cshtml
@model CheckList.Models.Check

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Check</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CheckDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckIsDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CheckIsDone)
                    @Html.ValidationMessageFor(model => model.CheckIsDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckDueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckDueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckDueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CheckList/Views/Checks/Delete.cshtml
@model CheckList.Models.Check

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Check</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CheckDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckIsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckIsDone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckDueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckDueDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CheckList/Views/Checks/Details.cshtml
@model CheckList.Models.Check

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Check</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CheckDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckIsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckIsDone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckDueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckDueDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CheckId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CheckList/Views/Checks/Edit.cshtml
@model CheckList.Models.Check

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Check</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CheckId)

        <div class="form-group">
            @Html.LabelFor(model => model.CheckDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckIsDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CheckIsDone)
                    @Html.ValidationMessageFor(model => model.CheckIsDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckDueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckDueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckDueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CheckList/Views/Checks/Index.cshtml
@model CheckList.Models.Check

@{
    ViewBag.Title = "Index";
}

<h2>Check List</h2>

<div id="checkTable"></div>

<div id="createNewCheck">
    @using (Ajax.BeginForm("AJAXCreate", "Checks",
                new AjaxOptions
                {
                    InsertionMode = InsertionMode.Replace,
                    HttpMethod = "POST",
                    UpdateTargetId = "checkTable"
                }
    ))
    {
        <div class="form-horizontal">
            <h4>Check</h4>
            <hr />
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CheckDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.EditorFor(model => model.CheckDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CheckDescription, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CheckDueDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.EditorFor(model => model.CheckDueDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CheckDueDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

@section Scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/BuildCheckTable.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

CheckList/Views/Checks/_CheckTable.cshtml
@model IEnumerable<CheckList.Models.Check>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

    <script language="text/javascript">
        var item = @Html.Raw(Json.Encode(ViewData["Item"]));
        var id = @Html.Raw(Json.Encode(ViewData["ItemId"]));
        if(item != ''){
            console.log(item); 
            alert("Due date for "+item);
            console.log(item); 
            $.ajax({
                url: '/Checks/UpdateCheckNotify/'+id,
                type: 'POST',
                success: function (result) {
                    console.log(result);
                }
            });
        }
    </script>
<div id="progressBarChecked">
    <div class="progress">
        <div class="progress-bar" role="progressbar" style="width:@(Html.AttributeEncode(ViewBag.Percent))%"></div>
    </div>
    <p>@(ViewBag.Percent)%</p>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CheckDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckIsDone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckDueDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (!item.CheckIsDone)
                {
                    @Html.DisplayFor(modelItem => item.CheckDescription)
                }
                else
                {
                    <div class="Checked">@Html.DisplayFor(modelItem => item.CheckDescription)</div>
                }

            </td>
            <td>
                @Html.CheckBoxFor(modelItem => item.CheckIsDone, new { id = item.CheckId, @class = "ActiveCheck" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckDueDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CheckId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CheckId })
            </td>
        </tr>
    }

</table>

<script src="~/Scripts/AddCheckBoxListener.js"></script>